# -----------------------------------------------------------------
# identity ${identity}
# -----------------------------------------------------------------
[identity.${identity}.rego_policy_agent]
identity = "${user}"
module = "pdo.identity.plugins.rego_policy_agent"
source = "${ContractFamily.Identity.rego_policy_agent.source}"
